version: '3.7'
services:
  k4li:
    hostname: k4li.hidd3n.ninja
    build:
      context: ./build/
      dockerfile: kalilinux.Dockerfile
    image: 'kalilinux:web'
    restart: always
    working_dir: /root
    environment:
      - SHELL=/bin/bash
      - VNC_PASSWORD=attack
    volumes:
      - /dev/null:/usr/share/novnc/index.html
      - ./script/kalilinux.startup.sh:/script/startup.sh
      - ./script/kalilinux.tunell.py:/script/tunell.py
      - /opt/docker/k4li/opt:/opt/resilience
      - /opt/docker/k4li/root:/root
    command: /bin/bash /script/startup.sh
    networks:
      hidd3n_lan:
        ipv4_address: 10.0.0.100


networks:
  hidd3n_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  filebeat_etc: {}
  filebeat_var: {}
  wazuh_api_configuration: {}
  wazuh_etc: {}
  wazuh_logs: {}
  wazuh_queue: {}
  wazuh_var_multigroups: {}
  wazuh_integrations: {}
  wazuh_active_response: {}
  wazuh_agentless: {}
  wazuh_wodles: {}
  wazuh-indexer-data: {}
