nodes:
  # Wazuh indexer server nodes
  indexer:
    - name: indexer.l4b
      ip: indexer.l4b.hidd3n.ninja

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: manager.l4b
      ip: manager.l4b.hidd3n.ninja

  # Wazuh dashboard node
  dashboard:
    - name: dashboard.l4b
      ip: dashboard.l4b.hidd3n.ninja