nodes:
  # Wazuh indexer server nodes
  indexer:
    - name: indexer.hidd3n
      ip: indexer.hidd3n

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: manager.hidd3n
      ip: manager.hidd3n

  # Wazuh dashboard node
  dashboard:
    - name: dashboard.hidd3n
      ip: dashboard.hidd3n